# Generated by Django 3.1.7 on 2021-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=6),
        ),
    ]
