# Generated by Django 3.1.7 on 2021-03-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
    ]
