# Generated by Django 3.1.7 on 2021-09-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210923_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='user',
        ),
    ]
