# Generated by Django 3.1.7 on 2021-09-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_mycart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mycart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
