# Generated by Django 3.1.7 on 2021-10-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210307_1734'),
        ('cart', '0005_auto_20210926_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.product'),
        ),
    ]
