# Generated by Django 3.1.7 on 2021-10-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210307_1734'),
        ('cart', '0006_auto_20211003_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
