# Generated by Django 3.1.7 on 2021-10-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_mycart_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mycart',
        ),
    ]
